version: "3"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "nodeapp"
      MYSQL_USER: "nodeapp"
      MYSQL_PASSWORD: "123456"
    volumes:
      - dbdata:/var/lib/mysql
  node:
    build:
      context: "./images/node"
      dockerfile: Dockerfile
    depends_on:
      - db
  web:
    image: nginx
    ports:
      - "8090:80"
    volumes:
      - "./images/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./images/node/web/public:/public"
    depends_on:
      - node
volumes:
  dbdata:
    driver: local
